version: '3.8'

services:
  frontend-principal:
    build:
      context: ./modulos/modulo-principal/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend-principal

  backend-principal:
    build:
      context: ./modulos/modulo-principal/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend-pronunciacion:
    build:
      context: ./modulos/modulo-pronunciacion/frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend-pronunciacion

  backend-pronunciacion:
    build:
      context: ./modulos/modulo-pronunciacion/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production

  frontend-caligrafia:
    build:
      context: ./modulos/modulo-caligrafia/frontend
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - backend-caligrafia

  backend-caligrafia:
    build:
      context: ./modulos/modulo-caligrafia/backend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production

networks:
  default:
    driver: bridge